import {
    NavigationItem,
} from "../../material/ui/items/navigation_item.slint";

import { Peripheral } from "../models/peripheral.slint";

// todo rename this to sidenavStore or similar
export global DevicesStoreSlint {
    in-out property <[string]> adapterInfos;
    in-out property <[NavigationItem]> adapterInfoNavItems;
    in-out property <[Peripheral]> peripherals;
    in-out property <[string]> adapters;

    callback onPeripheralConnect(peripheralId: string);
    callback onPeripheralDisconnect(peripheralId: string);
    callback onPeripheralClicked(peripheralId: string);

    callback onRescan();
}
