import {
    NavigationItem,
} from "../../material/ui/items/navigation_item.slint";

import { Peripheral } from "../models/peripheral.slint";
import { AdapterInfo } from "../models/adapter_info.slint";

export global SideNavigationStore {
    in-out property <[AdapterInfo]> adapterInfos: [{
        name: "mock hci0",
        long_name: "mock hci0 (usb:v1D6Bp0246d0556)",
    }];
    in-out property <[Peripheral]> peripherals: [
        {
            localname: "Infinix hahahihi",
            peripheralId: "1232",
            address: "askdfjls-asdfljasdf-j",
            isConnected: true,
            rssi: -20,
        },
        {
            localname: "Carga",
            peripheralId: "1234",
            address: "askdfjls-asdfljasdf-j",
            isConnected: false,
            rssi:-19,
        },
    ];

    in-out property <Peripheral> selected_peripheral;

    callback onPeripheralConnect(peripheralId: string);
    callback onPeripheralDisconnect(peripheralId: string);
    callback onPeripheralClicked(peripheralId: string);

    callback onRescan();
}
