import {
    CharacteristicPropertyFlag,
} from "./characteristic_property_flag.slint";
import {
    Descriptor,
} from "./descriptor.slint";
import { OptionString } from "../models/option_string.slint";


// @rust-attr(derive(serde::Serialize, serde::Deserialize))
export struct Characteristic{
  uuid: string,
  name: OptionString,
  description: OptionString,
  properties: [CharacteristicPropertyFlag],
}
