import { Peripheral } from "../models/peripheral.slint";
import {
    HorizontalDivider,
    IconButton,
    MaterialText,
} from "../../material/material.slint";
import { Icons } from "../icons/icons.slint";
import { SideNavigationStore } from "../stores/side_navigation_store.slint";
import {
    PeripheralNavigationItemTemplate,
} from "peripheral_navigation_item_template.slint";
import {
    MaterialTypography,
} from "../../material/ui/styling/material_typography.slint";
import {
    MaterialPalette,
} from "../../material/ui/styling/material_palette.slint";
import {
    MaterialStyleMetrics,
} from "../../material/ui/styling/material_style_metrics.slint";
import {
    MaterialAnimations,
} from "../../material/ui/styling/material_animations.slint";

component PeripheralDrawerHeader inherits VerticalLayout {
    in property <string> title;
    in property <string> subtitle;
    in-out property <image> icon;

    min_height: max(MaterialStyleMetrics.size_56, title_label.min_width);

    title_label := MaterialText {
        x: MaterialStyleMetrics.padding_16;
        text: root.title;
        color: MaterialPalette.on_surface_variant;
        vertical_alignment: center;
        style: MaterialTypography.title_medium_bold;
    }

    MaterialText {
        x: MaterialStyleMetrics.padding_16;
        text: root.subtitle;
        color: MaterialPalette.on_surface_variant;
        vertical_alignment: center;
        style: MaterialTypography.body_small;
    }
}

export component PeripheralNavigationGroupTemplate {
    in property <string> title;
    in property <string> subtitle;
    in property <[Peripheral]> peripherals;
    in property <int> current_index: -1;
    in property <bool> has_divider;

    callback select(index: int);

    VerticalLayout {
        alignment: start;

        HorizontalLayout {
            padding-right: 20px;
            padding-bottom: 10px;
            alignment: space-between;

            VerticalLayout {
                alignment: center;
                if root.title != 0:  PeripheralDrawerHeader {
                    title: root.title;
                    subtitle: root.subtitle;
                }
            }

            IconButton {
                icon: Icons.synchronize;
                tooltip: "Rescan";
            }
        }

        for item[index] in root.peripherals: PeripheralNavigationItemTemplate {
            icon: Icons.empty_filter;
            text: item.localname;
            selected: index == root.current_index;
            index: index;
            isConnected: item.isConnected;
            rssi: item.rssi;
            peripheralId: item.peripheralId;

            onConnect(peripheralId) => {
                SideNavigationStore.onPeripheralConnect(peripheralId);
            }
            onDisconnect(peripheralId) => {
                SideNavigationStore.onPeripheralDisconnect(peripheralId);
            }
            onClicked(peripheralId) => {
                SideNavigationStore.onPeripheralClicked(peripheralId);
            }
        }

        if root.has_divider: HorizontalDivider { }
    }
}
