export global Icons {
    out property <image> binoculars: @image-url("../icons/binoculars.svg");
    out property <image> bluetooth: @image-url("../icons/bluetooth.svg");
    out property <image> empty_filter: @image-url("../icons/empty_filter.svg");
    out property <image> gear_setting: @image-url("../icons/gear_setting.svg");
    out property <image> green_checkmark: @image-url("../icons/green_checkmark.svg");
    out property <image> synchronize: @image-url("../icons/synchronize.svg");
    out property <image> device: @image-url("../icons/device.svg");
    out property <image> service: @image-url("../icons/service.svg");
    out property <image> detail: @image-url("../icons/detail.svg");
    out property <image> save: @image-url("../icons/save.svg");
    out property <image> actions: @image-url("../icons/actions.svg");
    out property <image> hollowDot: @image-url("../icons/hollow_dot.svg");
    out property <image> send: @image-url("../icons/send.svg");
    out property <image> add: @image-url("../icons/add.svg");
    out property <image> questionMark: @image-url("../icons/question_mark.svg");
}
