import {
    FilledButton,
    ElevatedCard,
    MaterialWindowAdapter,
    Horizontal,
    Vertical,
    ElevatedCard,
    MaterialWindow,
    VerticalDivider,
} from "../material/material.slint";
import { SideNavigation } from "side_navigation.slint";
import { MainContent } from "main_content.slint";
import { DevicesStoreSlint } from "./stores/devices-stores.slint";
import { Button } from "std-widgets.slint";
import { HorizontalDivider } from "../material/ui/components/divider.slint";
import {
    NavigationItem,
} from "../material/ui/items/navigation_item.slint";

export { DevicesStoreSlint }

export component MainWindow inherits MaterialWindow {
    width: 1600px;
    height: 800px;

    Vertical {
        padding: 0px;

        Horizontal {
            height: root.height;
            SideNavigation { }

            VerticalDivider { }

            MainContent { }
        }
    }
}
