import {
    FilledButton,
    ElevatedCard,
    MaterialWindowAdapter,
    Horizontal,
    Vertical,
    ElevatedCard,
} from "../material/material.slint";
import { SideNavigation } from "side_navigation.slint";
import { MainContent } from "main_content.slint";

export component MainWindow inherits Window {
    width: 1200px;
    height: 800px;

    Vertical {
        padding: 0px;

        Horizontal {
            SideNavigation { }

            MainContent { }
        }
    }
}
