import {
    FilledButton,
    ElevatedCard,
    MaterialWindowAdapter,
    Horizontal,
    Vertical,
    ElevatedCard,
    MaterialWindow,
} from "../material/material.slint";
import { SideNavigation } from "side_navigation.slint";
import { MainContent } from "main_content.slint";
import { DevicesStoreSlint } from "./stores/devices-stores.slint";
import { Button } from "std-widgets.slint";
import { HorizontalDivider } from "../material/ui/components/divider.slint";
import {
    NavigationItem,
} from "../material/ui/items/navigation_item.slint";

export { DevicesStoreSlint }
export component MainWindow inherits MaterialWindow {
    width: 1200px;
    height: 800px;

    // Vertical {
    //     Text {
    //         text: "value is: " + Logic.the-value;
    //     }
    //
    //     for adap in Logic.adapter: Text {
    //         text: adap;
    //     }
    //
    //     Button {
    //         text: "get adapter info";
    //         clicked => {
    //             Logic.get_adapter_info()
    //         }
    //     }
    //
    //     Button {
    //         text: "click me";
    //         clicked => {
    //             Logic.magic-operation(1)
    //         }
    //     }
    // }

    Vertical {
        padding: 0px;

        Horizontal {

            SideNavigation { }

            HorizontalDivider { }

            Button {
                text: "get adapter info";
                clicked => {
                    Logic.get_adapter_info()
                }
            }
            // MainContent { }
        }
    }
}

export global Logic {
    in-out property <int> the-value;
    in-out property <[string]> adapter;
    pure callback magic-operation(int) -> int;
    pure callback get_adapter_info();
}
