import { ElevatedCard } from "../material/ui/components/card.slint";
import { Vertical, VerticalDivider } from "../material/material.slint";
import { Characteristic } from "./models/characteristic.slint";
import {
    CharacteristicPropertyFlag,
} from "./models/characteristic_property_flag.slint";

import { ServiceCharacteristics } from "service_characteristic.slint";
import { MoreAction } from "more_actions.slint";
export component MainContent inherits VerticalLayout {

    HorizontalLayout {
        ServiceCharacteristics {
            peripheralName: "Carga";
            services: [
                {
                    uuid: "0x1234",
                    primary: true,
                    name: {
                        hasValue: true,
                        value: "Heart Rate Service",
                    },
                    description: {
                        hasValue: false,
                        value: "",
                    },
                    characteristics: [
                        {
                            uuid: "0x8978",
                            name: { hasValue: false, value: "" },
                            description: { hasValue: true, value: "Really important characteristics" },
                            properties: [CharacteristicPropertyFlag.READ, CharacteristicPropertyFlag.WRITE],
                        },
                        {
                            uuid: "0x7810",
                            name: { hasValue: false, value: "" },
                            description: { hasValue: true, value: "Second Really important characteristics" },
                            properties: [
                                CharacteristicPropertyFlag.WRITE-WITHOUT-RESPONSE,
                                CharacteristicPropertyFlag.BROADCAST
                            ],
                        }
                    ],
                },
                {
                    uuid: "0x4321",
                    primary: false,
                    name: {
                        hasValue: true,
                        value: "HID - Human Machine Interface",
                    },
                    description: {
                        hasValue: true,
                        value: "really helpfull description for this services",
                    },
                    characteristics: [],
                },
                {
                    uuid: "0x4321",
                    primary: false,
                    name: {
                        hasValue: true,
                        value: "HID - Human Machine Interface",
                    },
                    description: {
                        hasValue: false,
                        value: "",
                    },
                    characteristics: [],
                },
                {
                    uuid: "0x4321",
                    primary: false,
                    name: {
                        hasValue: true,
                        value: "HID - Human Machine Interface",
                    },
                    description: {
                        hasValue: false,
                        value: "",
                    },
                    characteristics: [],
                },
            ];
        }

        VerticalDivider { }

        MoreAction { }
    }
}
