import { ElevatedCard } from "../material/material.slint";
import { Vertical } from "../material/material.slint";
import {
    NavigationDrawer,
} from "../material/ui/components/navigation_drawer.slint";

import {
    NavigationItem,
} from "../material/ui/items/navigation_item.slint";

import { DevicesStoreSlint } from "./stores/devices-stores.slint";
import { Button } from "std-widgets.slint";

export component SideNavigation {
    Vertical {
        Text {
            text: "Peripherals";
        }

        Button {
            text: "re-scan";
            clicked => {
                DevicesStoreSlint.onRescan()
            }
        }

        for p in DevicesStoreSlint.peripherals: Text {
            text: p.localname;
        }
    }
}
