import { ElevatedCard } from "../material/material.slint";
import {
    Vertical,
    MaterialText,
    Icon,
    ScrollView,
    IconButton,
} from "../material/material.slint";
import {
    NavigationDrawer,
} from "../material/ui/components/navigation_drawer.slint";
import {
    NavigationItem,
} from "../material/ui/items/navigation_item.slint";
import { Button } from "std-widgets.slint";
import {
    PeripheralNavigationGroupTemplate,
} from "navigations/peripheral_navigation_group_template.slint";
import {
    MaterialTypography,
} from "../material/ui/styling/material_typography.slint";
import { Icons } from "icons/icons.slint";
import { SideNavigationStore } from "./stores/side_navigation_store.slint";

component SideNavFooter inherits HorizontalLayout {
    height: 60px;
    alignment: start;
    padding-bottom: 15px;

    VerticalLayout {
        alignment: center;
        IconButton {
            icon: Icons.questionMark;
        }
    }

    VerticalLayout {
        alignment: center;
        MaterialText {
            text: "About";
            style: MaterialTypography.body_large;
        }
    }
}

export component SideNavigation inherits Vertical {
    width: 500px;
    height: 800px;
    padding-left: 15px;

    HorizontalLayout {
        VerticalLayout {
            alignment: center;
            Icon {
                source: Icons.bluetooth;
                height: 30px;
                width: 30px;
            }
        }

        MaterialText {
            text: "Available Adapter";
            style: MaterialTypography.title_large_bold;
        }
    }

    ScrollView {
        VerticalLayout {
            alignment: start;

            for adapter in SideNavigationStore.adapters: PeripheralNavigationGroupTemplate {
                title: adapter + " Devices";
                peripherals: SideNavigationStore.peripherals;
            }
        }
    }

    SideNavFooter { }
}
